# Generated by Django 2.2.5 on 2022-01-29 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='friends_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('birthday', models.DateField(max_length=32)),
                ('hobby', models.CharField(max_length=64)),
            ],
        ),
    ]
