# Generated by Django 2.2.5 on 2022-01-30 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friends_info',
            name='birthday',
            field=models.DateField(max_length=64),
        ),
        migrations.AlterField(
            model_name='friends_info',
            name='hobby',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='friends_info',
            name='name',
            field=models.CharField(max_length=64),
        ),
    ]
